import type { Metadata } from "next";
import { Inter, Noto_Sans_Gothic } from "next/font/google";
import "./globals.css";
import SessionProvider from "@/components/providers/SessionProvider";
import RqProvider from "@/components/providers/RqProvider";
import { CounterStoreProvider } from "@/components/providers/ZustandProvider";

const inter = Inter({ subsets: ["latin"] });

const natoSans = Noto_Sans_Gothic({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "x.무슨일이 일어나고 있나요?",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={natoSans.className}>
        <SessionProvider>
          <CounterStoreProvider>
            <RqProvider>{children}</RqProvider>
          </CounterStoreProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
