import type { Metadata } from "next";
import { Inter, Noto_Sans_Gothic } from "next/font/google";
import "./globals.css";
import MSWComponent from "./_component/MSWComponent";
import SessionProvider from "@/components/providers/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

const natoSans = Noto_Sans_Gothic({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={natoSans.className}>
        <MSWComponent />
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
